from django.contrib import admin
from django.urls import path
from . import views
from .views import grafico_tiempo_usuario, grafico_tiempo_admin


urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path("lista_peliculas/", views.lista_peliculas, name='lista_peliculas'),
    path('lista_series/', views.lista_series, name='lista_series'),
    path("home2/", views.home2, name='home2'),
    path("marcar_pelicula_favorita/<int:pelicula_id>/", views.marcar_pelicula_favorita, name='marcar_pelicula_favorita'),
    path("marcar_pelicula_vista/<int:pelicula_id>/", views.marcar_pelicula_vista, name='marcar_pelicula_vista'),
    path("marcar_serie_favorita/<int:serie_id>/", views.marcar_serie_favorita, name='marcar_serie_favorita'),
    path("marcar_serie_vista/<int:serie_id>/", views.marcar_serie_vista, name='marcar_serie_vista'),
    path("peliculas_favoritas/", views.peliculas_favoritas, name='peliculas_favoritas'),
    path("peliculas_vistas/", views.peliculas_vistas, name='peliculas_vistas'),
    path("detalle_pelicula/<int:pelicula_id>/<int:pelicula_categoria_id>/", views.detalle_pelicula, name='detalle_pelicula'),
    path("detalle_serie/<int:serie_id>/<int:serie_categoria_id>/", views.detalle_serie, name='detalle_serie'),
    path("series_favoritas/", views.series_favoritas, name='series_favoritas'),
    path("series_vistas/", views.series_vistas, name='series_vistas'),
    path("logout/", views.signout, name='signout'),
    path("categorias_peliculas/", views.categorias_peliculas, name='categorias_peliculas'),
    path("categorias_series/", views.categorias_series, name='categorias_series'),
    path("peliculas_categorizadas/<int:categoria_id>/", views.peliculas_categorizadas, name='peliculas_categorizadas'),
    path("series_categorizadas/<int:categoria_id>/", views.series_categorizadas, name='series_categorizadas'),
    path("buscar_pelicula/", views.buscar_pelicula, name='buscar_pelicula'),
    path("buscar_serie/", views.buscar_serie, name='buscar_serie'),
    path("grafico_tiempo_usuario/", grafico_tiempo_usuario, name='grafico_tiempo_usuario'),
    path("tiempo-usuarios/", grafico_tiempo_admin, name='grafico_tiempo_admin'),
    path("buscar_peliculas_categorizadas/<int:categoria_id>", views.buscar_peliculas_categorizadas, name='buscar_peliculas_categorizadas'),
    path("buscar_peliculas_favoritas/", views.buscar_peliculas_favoritas, name='buscar_peliculas_favoritas'),
    path("buscar_peliculas_vistas/", views.buscar_peliculas_vistas, name='buscar_peliculas_vistas'),
    path("buscar_series_categorizadas/<int:categoria_id>", views.buscar_series_categorizadas, name='buscar_series_categorizadas'),
    path("buscar_series_favoritas/", views.buscar_series_favoritas, name='buscar_series_favoritas'),
    path("buscar_series_vistas/", views.buscar_series_vistas, name='buscar_series_vistas'),
    path("peliculas_por_año/", views.peliculas_por_año, name='peliculas_por_año'),
    path("peliculas_por_duracion/", views.peliculas_por_duracion, name='peliculas_por_duracion'),
    path("peliculas_categorizadas_por_año/<int:categoria_id>/", views.peliculas_categorizadas_por_año, name='peliculas_categorizadas_por_año'),
    path("peliculas_categorizadas_por_duracion/<int:categoria_id>/", views.peliculas_categorizadas_por_duracion, name='peliculas_categorizadas_por_duracion'),
    path("peliculas_favoritas_por_año/", views.peliculas_favoritas_por_año, name='peliculas_favoritas_por_año'),
    path("peliculas_favoritas_por_duracion/", views.peliculas_favoritas_por_duracion, name='peliculas_favoritas_por_duracion'),
    path("peliculas_vistas_por_año/", views.peliculas_vistas_por_año, name='peliculas_vistas_por_año'),
    path("peliculas_vistas_por_duracion/", views.peliculas_vistas_por_duracion, name='peliculas_vistas_por_duracion'),
    path("series_por_año/", views.series_por_año, name='series_por_año'),
    path("series_por_duracion/", views.series_por_duracion, name='series_por_duracion'),
    path("series_categorizadas_por_año/<int:categoria_id>/", views.series_categorizadas_por_año, name='series_categorizadas_por_año'),
    path("series_categorizadas_por_duracion/<int:categoria_id>/", views.series_categorizadas_por_duracion, name='series_categorizadas_por_duracion'),
    path("series_favoritas_por_año/", views.series_favoritas_por_año, name='series_favoritas_por_año'),
    path("series_favoritas_por_duracion/", views.series_favoritas_por_duracion, name='series_favoritas_por_duracion'),
    path("series_vistas_por_año/", views.series_vistas_por_año, name='series_vistas_por_año'),
    path("series_vistas_por_duracion/", views.series_vistas_por_duracion, name='series_vistas_por_duracion'),
    path("buscar_peliculas_por_anio/", views.buscar_peliculas_por_anio, name='buscar_peliculas_por_anio'),
    path("buscar_peliculas_por_duracion/", views.buscar_peliculas_por_duracion, name='buscar_peliculas_por_duracion'),
    path("buscar_peliculas_categorizadas_por_anio/<int:categoria_id>/", views.buscar_peliculas_categorizadas_por_anio, name='buscar_peliculas_categorizadas_por_anio'),
    path("buscar_peliculas_categorizadas_por_duracion/<int:categoria_id>/", views.buscar_peliculas_categorizadas_por_duracion, name='buscar_peliculas_categorizadas_por_duracion'),
    path("buscar_peliculas_favoritas_por_anio/", views.buscar_peliculas_favoritas_por_anio, name='buscar_peliculas_favoritas_por_anio'),
    path("buscar_peliculas_favoritas_por_duracion/", views.buscar_peliculas_favoritas_por_duracion, name='buscar_peliculas_favoritas_por_duracion'),
    path("buscar_peliculas_vistas_por_anio/", views.buscar_peliculas_vistas_por_anio, name='buscar_peliculas_vistas_por_anio'),
    path("buscar_peliculas_vistas_por_duracion/", views.buscar_peliculas_vistas_por_duracion, name='buscar_peliculas_vistas_por_duracion'),
    path("buscar_series_por_anio/", views.buscar_series_por_anio, name='buscar_series_por_anio'),
    path("buscar_series_por_duracion/", views.buscar_series_por_duracion, name='buscar_series_por_duracion'),
    path("buscar_series_categorizadas_por_anio/<int:categoria_id>/", views.buscar_series_categorizadas_por_anio, name='buscar_series_categorizadas_por_anio'),
    path("buscar_series_categorizadas_por_duracion/<int:categoria_id>/", views.buscar_series_categorizadas_por_duracion, name='buscar_series_categorizadas_por_duracion'),
    path("buscar_series_favoritas_por_anio/", views.buscar_series_favoritas_por_anio, name='buscar_series_favoritas_por_anio'),
    path("buscar_series_favoritas_por_duracion/", views.buscar_series_favoritas_por_duracion, name='buscar_series_favoritas_por_duracion'),
    path("buscar_series_vistas_por_anio/", views.buscar_series_vistas_por_anio, name='buscar_series_vistas_por_anio'),
    path("buscar_series_vistas_por_duracion/", views.buscar_series_vistas_por_duracion, name='buscar_series_vistas_por_duracion'),
]