# Generated by Django 5.1.6 on 2025-03-03 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='peliculas')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('duracion', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('vista', models.BooleanField(default=False)),
                ('favorita', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='series')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('temporadas', models.IntegerField()),
                ('numero_capitulos', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('vista', models.BooleanField(default=False)),
                ('favorita', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
