# Generated by Django 5.1.6 on 2025-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria_alter_pelicula_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
