# Generated by Django 5.1.6 on 2025-03-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='user',
        ),
    ]
