# Generated by Django 5.1.6 on 2025-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_pelicula_user_remove_serie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='año',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
