# Generated by Django 5.1.6 on 2025-03-04 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pelicula_año_pelicula_director_serie_año_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='favorita',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='vista',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='favorita',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='vista',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='favorita',
            field=models.ManyToManyField(default=False, related_name='pelicula_favorita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='vista',
            field=models.ManyToManyField(default=False, related_name='pelicula_vista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='favorita',
            field=models.ManyToManyField(default=False, related_name='serie_favorita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='vista',
            field=models.ManyToManyField(default=False, related_name='serie_vista', to=settings.AUTH_USER_MODEL),
        ),
    ]
