# Generated by Django 5.1.6 on 2025-03-04 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_pelicula_favorita_alter_pelicula_vista_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='favorita',
            field=models.ManyToManyField(blank=True, related_name='peliculas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='vista',
            field=models.ManyToManyField(blank=True, related_name='peliculas_vistas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serie',
            name='favorita',
            field=models.ManyToManyField(blank=True, related_name='series_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serie',
            name='vista',
            field=models.ManyToManyField(blank=True, related_name='series_vistas', to=settings.AUTH_USER_MODEL),
        ),
    ]
