# Generated by Django 5.1.6 on 2025-03-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_serie_duracion_capitulos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='director',
            new_name='creador_creadores',
        ),
    ]
